### ISSUE TITLE
More Entries shown when none are available

### ISSUE THREAD

**Issue by thehabes** [thehabes/DigiSig#21]
Hide the 'More Entries' button if there are no more entries

**Comment by thehabes** [comment]
I did not write this code, but I found the problem lines:

if($numberofresults <= 100){
                    echo row with button and settings_1
                }
else{
                    echo row with button and settings_2
                }

I comment out the first echo, because if there are 100 or less results we do not need to show the button.  However, at the bottom of lists with more than 100 results, the row disappears.  commenting out the 2nd echo seems to have no effect.  I will need Han to look at it.

**Comment by dennis21cn** [comment]
That's my code, It's fIxed.

**Comment by thehabes** [comment]
Tested, working.
