### ISSUE TITLE
Design Conept: Abbreviated Text

### ISSUE THREAD

**Issue by thehabes** [thehabes/DigiSig#22]
There is too much abbreviation of the text in the search results themselves. Perhaps we could consider doubling the amount of text displayed before (more) appears?

**Comment by thehabes** [comment]
Definitely doable

**Comment by dennis21cn** [comment]
I changed it to 100.

**Comment by thehabes** [comment]
The code the gets the descriptions from the row always gets descriptions that == "".  I cannot see the changes to this because this is for descriptions.  Something has happened with the data.

**Comment by thehabes** [comment]
Works
