### ISSUE TITLE
Total Results not populated correctly

### ISSUE THREAD

**Issue by thehabes** [thehabes/DigiSig#23]
At the top of each search result table is displayed the number of results. Could we adjust this number to reflect the total number returned by the query and not just the number displayed on the screen? At the moment it is saying ‘100’ even when I know the result should be something much larger.

**Comment by johnmcewan** [comment]
I believe (and this might be wrong) that there is a function in PHP that allows you to query for the number of rows that a query will return without actually returning the result. I would then assign the count to the string that displays on the screen.

**Comment by thehabes** [comment]
Tested, still needs to be fixed

**Comment by thehabes** [comment]
tested, fixed
