### ISSUE TITLE
Seal Page -- descriptions

### ISSUE THREAD

**Issue by johnmcewan** [thehabes/DigiSig#51]
On the 'Seal' page the title of the sub section 'other descriptions' should be changed to simply 'Descriptions'. This is because this section contains links that take you to the 'Seal Description' page.

![screenshot 5](https://cloud.githubusercontent.com/assets/13589952/9335465/108c457c-4589-11e5-9223-0fc728618bf7.png)

**Comment by thehabes** [comment]
other descriptions has been changed to descriptions
