### ISSUE TITLE
seal description page -- other descriptions

### ISSUE THREAD

**Issue by johnmcewan** [thehabes/DigiSig#53]
Would it be possible to omit the 'other descriptions' bar at the bottom of the page when there are no 'other descriptions'? This would make the page a bit cleaner.

![screenshot 4](https://cloud.githubusercontent.com/assets/13589952/9335704/6cb6455e-458a-11e5-8451-512ebdcf430c.png)

**Comment by thehabes** [comment]
Yes, this area will now hide with no result returns
