### ISSUE TITLE
seal descriptions -- x and y

### ISSUE THREAD

**Issue by johnmcewan** [thehabes/DigiSig#54]
On the seal description page -- the dimensions of the seal are being present as 'Size Y' and 'Size X'. COuld we change that to 'Height' and 'Width'. Most of my users are pretty old school.

![screenshot 8](https://cloud.githubusercontent.com/assets/13589952/9335774/e19081dc-458a-11e5-93fb-537389c33617.png)

**Comment by thehabes** [comment]
Size Y is now Height
Size X is now Width
