### ISSUE TITLE
item page -- list of indexes

### ISSUE THREAD

**Issue by johnmcewan** [thehabes/DigiSig#55]
Could we find someway to distinguish the subsection headings in the list of indexes -- 'Catalogue' and 'Repository' ? At the moment they are greyed out so they don't really work as guides for users. I might suggest giving them a more visible tone, perhaps indenting them slightly, and maybe bolding or italizing? This way people will be able to see immediately that there are two sections in the list. 

![Uploading Screenshot (3).png…]()

**Comment by thehabes** [comment]
Bolded, colored, padded
