### ISSUE TITLE
view seal entry link

### ISSUE THREAD

**Issue by johnmcewan** [thehabes/DigiSig#71]
The 'view seal entry' link  -- line 374 -- now appears on the same line as the title of the page. 

Could we reposition the 'view seal entry' link so that it appears immediately below the box that contains all the seal description information but not within it? So the 'view seal entry' button will appear within the area defined by the two thin horizontal lines  but below all the information that forms the seal description itself.

**Comment by thehabes** [comment]
It has been moved immediately below the box that contains all the seal description information.  tested.
