### ISSUE TITLE
RTI failures

### ISSUE THREAD

**Issue by johnmcewan** [thehabes/DigiSig#94]
The RTIs aren’t working when called by specifying their ID number as part of the URL (in the form of gallery/{number} ). But they do work when the URL is simply digisig/gallery (with no numbers specified). 

Things I have tried to identify the cause of the bug:

1)	Tested to make sure other RTIs work when specified as the default. (when no RTI is specified in the URL the code is supposed to call a hard coded default RTI). Other RTIs work just as well as the current default RTI so the RTI files themselves do not seem to be at fault.
2)	Tested to see if when a page is loaded and an RTI other than the default is requested if the query to get the right folder details is failing. I put ‘digisig/gallery/11887694’ in through the search bar and found that the code queries the correct folder name and passes that info to the javascript  ($val1_directory). Again no problem there. 
3)	Tested to see if the mechanism whereby information is passed to the javascript is failing. I hard coded $val1_directory to a valid directory name. The default RTI continues to work when loaded as ‘gallery’ and continues to fail when loaded as digisig/gallery/11887234 (entity number). 

The only difference I can see in the case of success and failure is the form of the URL. I don’t see why that should matter but it seems to.

**Comment by johnmcewan** [comment]
Bryan -- thanks for that. That is what I suspected, given our previous experience with digisig. 

But in the meantime, what we need is a fix to get the RTIs working, if only temporarily. Can we tell force the RTI viewer to look for the RTI files in a specific location? I don't know enough about how the viewer works to make that change.

**Comment by cubap** [comment]
yeah,
We found the issue may be with some requirements about how to refer to the public directories. I'm making the changes to see if I can fix it.
